### ISSUE TITLE
Not enough gyatt 

### ISSUE THREAD

**Issue by GarbageBob** [SahalMoh/AtmosfarDesktop#8]
Add gyatt to the app
![RDT_20240520_1129532710294330612402228](https://github.com/SahalMoh/AtmosfarDesktop/assets/126862594/ca71cf9e-8290-4bfa-9169-b64aedc04d2a)

**Comment by SahalMoh** [comment]
App Has Gyatten Enough Gyatt. I Am Not DOING This 😡😡😡😡😡😡😡😡
